version: '3'

services:
  db:
    image: mariadb:10.0.33
    container_name: tandb01
    ports:
      - 3307:3306
    volumes:
      - /opt/tan/dbdata:/var/lib/mysql
      - /opt/tan/dbconfig:/etc/mysql/conf.d
